### ISSUE TITLE
THE SAME ERROR WITH HEROKU

### ISSUE THREAD

**Issue by imatrixgp** [corbindavenport/tootbot#54] opened 2018-06-27 21:03 UTC
I
   fortnitebrbest
      
Application Logs
2018-06-27T21:00:22.463075+00:00 app[worker.1]:     'http', request, response, code, msg, hdrs)
2018-06-27T21:00:22.463081+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 570, in error
2018-06-27T21:00:22.463366+00:00 app[worker.1]:     return self._call_chain(*args)
2018-06-27T21:00:22.463372+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 504, in _call_chain
2018-06-27T21:00:22.463638+00:00 app[worker.1]:     result = func(*args)
2018-06-27T21:00:22.463644+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 650, in http_error_default
2018-06-27T21:00:22.463945+00:00 app[worker.1]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2018-06-27T21:00:22.463994+00:00 app[worker.1]: urllib.error.HTTPError: HTTP Error 429: Too Many Requests
2018-06-27T21:00:22.563339+00:00 heroku[worker.1]: Process exited with status 1
2018-06-27T21:00:23.733860+00:00 heroku[worker.1]: State changed from up to crashed
2018-06-27T21:02:15.270633+00:00 heroku[worker.1]: State changed from crashed to starting
2018-06-27T21:02:19.568207+00:00 heroku[worker.1]: Starting process with command `python tootbot-heroku.py`
2018-06-27T21:02:20.242068+00:00 heroku[worker.1]: State changed from starting to up
2018-06-27T21:02:22.481371+00:00 app[worker.1]: [ OK ] You have the latest version of Tootbot (2.2)
2018-06-27T21:02:22.481511+00:00 app[worker.1]: [ OK ] Attempting to log in to Twitter...
2018-06-27T21:02:22.757902+00:00 app[worker.1]: [ OK ] Sucessfully authenticated on Twitter as @FortniteBRBest
2018-06-27T21:02:22.758142+00:00 app[worker.1]: [ OK ] cache.csv file not found, created a new one
2018-06-27T21:02:22.758145+00:00 app[worker.1]: [ OK ] Setting up connection with Reddit...
2018-06-27T21:02:23.027426+00:00 app[worker.1]: [ OK ] Getting posts from Reddit...
2018-06-27T21:02:23.311415+00:00 app[worker.1]: [ OK ] media folder not found, created a new one
2018-06-27T21:02:23.589212+00:00 app[worker.1]: [EROR] URL does not point to a valid image file.
2018-06-27T21:02:23.589230+00:00 app[worker.1]: [ OK ] Ignoring 8u91rn because non-media posts are disabled or there was not a valid media file downloaded
2018-06-27T21:02:24.556550+00:00 app[worker.1]: [EROR] URL does not point to a valid image file.
2018-06-27T21:02:24.556804+00:00 app[worker.1]: [ OK ] Ignoring 8ucjjt because non-media posts are disabled or there was not a valid media file downloaded
2018-06-27T21:02:25.005370+00:00 app[worker.1]: Traceback (most recent call last):
2018-06-27T21:02:25.005384+00:00 app[worker.1]:   File "tootbot-heroku.py", line 237, in <module>
2018-06-27T21:02:25.005681+00:00 app[worker.1]:     make_post(post_dict)
2018-06-27T21:02:25.005685+00:00 app[worker.1]:   File "tootbot-heroku.py", line 101, in make_post
2018-06-27T21:02:25.005807+00:00 app[worker.1]:     post_dict[post][2], IMGUR_CLIENT, IMGUR_CLIENT_SECRET)
2018-06-27T21:02:25.005842+00:00 app[worker.1]:   File "/app/getmedia.py", line 154, in get_media
2018-06-27T21:02:25.005998+00:00 app[worker.1]:     img_site = urlopen(img_url)
2018-06-27T21:02:25.006003+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 223, in urlopen
2018-06-27T21:02:25.006242+00:00 app[worker.1]:     return opener.open(url, data, timeout)
2018-06-27T21:02:25.006246+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 532, in open
2018-06-27T21:02:25.006610+00:00 app[worker.1]:     response = meth(req, response)
2018-06-27T21:02:25.006613+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 642, in http_response
2018-06-27T21:02:25.006905+00:00 app[worker.1]:     'http', request, response, code, msg, hdrs)
2018-06-27T21:02:25.006909+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 564, in error
2018-06-27T21:02:25.007181+00:00 app[worker.1]:     result = self._call_chain(*args)
2018-06-27T21:02:25.007184+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 504, in _call_chain
2018-06-27T21:02:25.007422+00:00 app[worker.1]:     result = func(*args)
2018-06-27T21:02:25.007425+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 756, in http_error_302
2018-06-27T21:02:25.007744+00:00 app[worker.1]:     return self.parent.open(new, timeout=req.timeout)
2018-06-27T21:02:25.007748+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 532, in open
2018-06-27T21:02:25.008003+00:00 app[worker.1]:     response = meth(req, response)
2018-06-27T21:02:25.008004+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 642, in http_response
2018-06-27T21:02:25.008307+00:00 app[worker.1]:     'http', request, response, code, msg, hdrs)
2018-06-27T21:02:25.008312+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 564, in error
2018-06-27T21:02:25.008593+00:00 app[worker.1]:     result = self._call_chain(*args)
2018-06-27T21:02:25.008596+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 504, in _call_chain
2018-06-27T21:02:25.008895+00:00 app[worker.1]:     result = func(*args)
2018-06-27T21:02:25.008900+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 756, in http_error_302
2018-06-27T21:02:25.009221+00:00 app[worker.1]:     return self.parent.open(new, timeout=req.timeout)
2018-06-27T21:02:25.009224+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 532, in open
2018-06-27T21:02:25.009479+00:00 app[worker.1]:     response = meth(req, response)
2018-06-27T21:02:25.009482+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 642, in http_response
2018-06-27T21:02:25.009764+00:00 app[worker.1]:     'http', request, response, code, msg, hdrs)
2018-06-27T21:02:25.009766+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 570, in error
2018-06-27T21:02:25.010085+00:00 app[worker.1]:     return self._call_chain(*args)
2018-06-27T21:02:25.010087+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 504, in _call_chain
2018-06-27T21:02:25.010348+00:00 app[worker.1]:     result = func(*args)
2018-06-27T21:02:25.010350+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/urllib/request.py", line 650, in http_error_default
2018-06-27T21:02:25.010614+00:00 app[worker.1]:     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2018-06-27T21:02:25.010651+00:00 app[worker.1]: urllib.error.HTTPError: HTTP Error 429: Too Many Requests
2018-06-27T21:02:25.128197+00:00 heroku[worker.1]: State changed from up to crashed
2018-06-27T21:02:25.094506+00:00 heroku[worker.1]: Process exited with status 1

**Comment by corbindavenport** [comment] 2018-06-28 02:33
Closing because this is a duplicate of #51

**Closed by corbindavenport** 2018-06-28 02:33 UTC
